["Repos/oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["Repos/oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["Repos/oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["Repos/oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1
[".config/nvim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-zoxide"]
    type = "git-repo"
    url = "https://github.com/jchook/ranger-zoxide.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-fzf-filter"]
    type = "git-repo"
    url = "https://github.com/MuXiu1997/ranger-fzf-filter.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-fzf-marks"]
    type = "git-repo"
    url = "https://github.com/laggardkernel/ranger-fzf-marks.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-archives"]
    type = "git-repo"
    url = "https://github.com/maximtrp/ranger-archives.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-cmus"]
    type = "git-repo"
    url = "https://github.com/maximtrp/ranger-cmus.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-devicons"]
    type = "git-repo"
    url = "https://github.com/alexanderjeurissen/ranger_devicons.git"
    refreshPeriod = "168h"
["Repos/h-m-m"]
    type = "git-repo"
    url = "https://github.com/nadrad/h-m-m.git"
    refreshPeriod = "168h"
 ["Repos/ytfzf"]
    type = "git-repo"
    url = "https://github.com/pystardust/ytfzf.git"
    refreshPeriod = "168h"
